Fix broken tests by changing the way we vendor code
When I configured the project to use vndr and I broke the unit tests.

The tests were failing with these errors:

```
github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/builtin/providers/ignition

vendor/github.com/hashicorp/terraform/builtin/providers/ignition/provider.go:92:
undefined: types.SystemdUnit

vendor/github.com/hashicorp/terraform/builtin/providers/ignition/provider.go:93:
undefined: types.NetworkdUnit

vendor/github.com/hashicorp/terraform/builtin/providers/ignition/provider.go:94:
undefined: types.User

vendor/github.com/hashicorp/terraform/builtin/providers/ignition/provider.go:95:
undefined: types.Group
```

You can see the full log here:
https://travis-ci.org/dmacvicar/terraform-provider-libvirt

Terraform upstream doesn't have this problem because it vendors coreos ignition,
which has all these types defined inside of `vendor/github.com/coreos/ignition/config/types/unit.go`.

It turns out vndr is removing this file from our vendored terraform sources.

I tried to use the whitelist option to prevent that from happening but it didn't
work.
Moreover, it looks like the whitelists are not stored into the
`vendor.conf`, which means we would have to pass the flag every time we
interact with the vendor code!

With this commit we move from using vndr to use glide, which is not
affected by this issue.

Signed-off-by: Flavio Castelli <fcastelli@suse.com>