examples: Fix 'autoport' value from string to boolean
The schema was changed to require a boolean value for the 'autoport'
argument. Fixes the following error:

Error: libvirt_domain.domain-ubuntu: graphics.0.autoport: cannot parse '' as bool: strconv.ParseBool: parsing "yes": invalid syntax